=== xinzf/goflow.v2/test/config/goflow.dtd
<?xml version="1.0" encoding="utf-8" ?>
<!ELEMENT workflow (steps,joins*,splits*)>

<!ATTLIST workflow
        id CDATA #REQUIRED
        name CDATA #REQUIRED
        describe CDATA #REQUIRED
        version CDATA #REQUIRED
        >

<!ELEMENT steps (step+) >
<!ATTLIST steps
        start CDATA #REQUIRED
        end CDATA #REQUIRED
        start-init-status #REQUIRED
        >

<!ELEMENT step (
        restrict?,
        pre-functions?,
        actions,
        post-functions?) >

<!ATTLIST step
        id CDATA #REQUIRED
        name CDATA #REQUIRED
        >

<!ELEMENT restrict (conditions) >
<!ATTLIST restrict
        message CDATA #IMPLIED
        >

<!ELEMENT conditions (function?)+ >
<!ATTLIST conditions
        type (AND | OR) #IMPLIED
        >

<!ELEMENT function (arg*) >
<!ATTLIST function
        name CDATA #REQUIRED
        want (true | false) #IMPLIED
        >

<!ELEMENT arg (#PCDATA) >
<!ATTLIST arg name CDATA #REQUIRED >

<!--<!ELEMENT bean (#PCDATA) >-->

<!ELEMENT pre-functions (function+) >

<!ELEMENT post-functions (function+) >

<!ELEMENT actions (restrict?,action+) >

<!ELEMENT action (restrict?,pre-functions?,results,post-functions?) >

<!ATTLIST action
        name CDATA #REQUIRED
        text CDATA #REQUIRED
        auto (true | false) #IMPLIED
        >

<!ELEMENT results (result*,default-result*) >
<!ELEMENT result (conditions,owners?) >
<!ELEMENT default-result (conditions?,owners?) >
<!ATTLIST result
        exit-status CDATA #IMPLIED
        status CDATA #IMPLIED
        step CDATA #IMPLIED
        split CDATA #IMPLIED
        join CDATA #IMPLIED
        due-seconds CDATA #IMPLIED
        >
<!ATTLIST default-result
        exit-status CDATA #IMPLIED
        status CDATA #IMPLIED
        step CDATA #IMPLIED
        split CDATA #IMPLIED
        join CDATA #IMPLIED
        due-seconds CDATA #IMPLIED
        >

<!ELEMENT owners (owner+) >
<!ELEMENT owner EMPTY >
<!ATTLIST owner
        type (creator | caller | leader | users | deps | roles | none | variable) #REQUIRED
        props CDATA #IMPLIED
        >

<!ELEMENT joins (join+) >
<!ELEMENT join (results?) >
<!ATTLIST join
        id CDATA #REQUIRED
        >

<!ELEMENT splits (split+) >
<!ELEMENT split (results?) >
<!ATTLIST split id CDATA #REQUIRED >

=== xinzf/goflow.v2/test/config/workflow.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE workflow SYSTEM "goflow.dtd" >
<workflow id="bldz-20190516" version="1" describe="不良垫资" name="不良垫资">
    <steps start="1" end="16" start-init-status="created">
        <step id="1" name="初录">
            <actions>
                <action name="draft" text="暂存">
                    <results>
                        <default-result step="-1" status="draft">
                            <owners>
                                <owner type="caller" />
                            </owners>
                        </default-result>
                    </results>
                </action>
                <action name="submit" text="提交">
                    <pre-functions>
                        <function name="copyTo">
                            <arg name="users">17,18,19</arg>
                        </function>
                    </pre-functions>
                    <results>
                        <default-result step="2" status="queue" exit-status="done" due-seconds="7200">
                            <owners>
                                <owner type="leader"/>
                            </owners>
                        </default-result>
                    </results>
                </action>
            </actions>
        </step>
        <step id="2" name="初价">
            <actions>
                <!--<restrict message="当前状态不允许次操作或无权操作">-->
                    <!--<conditions type="AND">-->
                        <!--<function name="matchState" want="true">-->
                            <!--<arg name="step_id">${curr_step_id}</arg>-->
                            <!--<arg name="state">doing</arg>-->
                        <!--</function>-->
                    <!--</conditions>-->
                <!--</restrict>-->

                <action name="rollback" text="回退">
                    <results>
                        <default-result step="1" exit-status="done" status="supplement">
                            <owners>
                                <owner type="creator"/>
                            </owners>
                        </default-result>
                    </results>
                </action>
                <action name="reject" text="拒绝">
                    <results>
                        <default-result status="done" step="-2" />
                    </results>
                </action>
                <action name="success" text="报初价">
                    <results>
                        <default-result split="1" exit-status="done" />
                    </results>
                </action>
            </actions>
        </step>
        <step id="3" name="详录">
            <actions>
                <restrict message="当前状态不可进行此操作">
                    <conditions>
                        <function name="matchState" want="true">
                            <arg name="step_id">${curr_step_id}</arg>
                            <arg name="state">doing</arg>
                        </function>
                    </conditions>
                </restrict>

                <action name="draft" text="暂存">
                    <results>
                        <default-result step="-1" />
                    </results>
                </action>
                <action name="submit" text="提交">
                    <results>
                        <default-result join="1" exit-status="done" />
                    </results>
                </action>
            </actions>
        </step>
        <step id="4" name="面签">
            <actions>
                <action name="dead" text="未成交">
                    <results>
                        <default-result exit-status="done" step="-2" />
                    </results>
                </action>
                <action name="deal" text="成交">
                    <results>
                        <default-result join="1" exit-status="done" />
                    </results>
                </action>
            </actions>
        </step>
        <step id="5" name="自动拆分审核">
            <actions>
                <action name="auto" text="auto_1" auto="true">
                    <results>
                        <default-result split="2" exit-status="done" />
                    </results>
                </action>
            </actions>
        </step>
        <step id="6" name="风险审核">
            <actions>
                <restrict>
                    <conditions>
                        <function name="matchState">
                            <arg name="step_id">${curr_step_id}</arg>
                            <arg name="state">doing</arg>
                        </function>
                    </conditions>
                </restrict>
                <action name="rollback" text="回退">
                    <results>
                        <default-result exit-status="done" step="${rollback_id}" status="supplement">
                            <owners>
                                <owner type="variable" props="${rollback_uid}"/>
                            </owners>
                        </default-result>
                    </results>
                </action>
                <action name="reject" text="拒绝">
                    <results>
                        <default-result exit-status="done" status="-2" />
                    </results>
                </action>
                <action name="success" text="通过">
                    <results>
                        <default-result exit-status="done" join="2" />
                    </results>
                </action>
            </actions>
        </step>
        <step id="7" name="财务审核">
            <actions>
                <action name="rollback" text="回退">
                    <results>
                        <default-result exit-status="done" step="${rollback_id}" status="supplement">
                            <owners>
                                <owner type="variable" props="${rollback_uid}"/>
                            </owners>
                        </default-result>
                    </results>
                </action>
                <action name="reject" text="拒绝">
                    <results>
                        <default-result exit-status="done" status="-2" />
                    </results>
                </action>
                <action name="success" text="通过">
                    <results>
                        <default-result exit-status="done" join="2" />
                    </results>
                </action>
            </actions>
        </step>
        <step id="8" name="经理审批">
            <actions>
                <action name="rollback" text="回退">
                    <results>
                        <default-result exit-status="done" step="${rollback_id}" status="supplement">
                            <owners>
                                <owner type="variable" props="${rollback_uid}"/>
                            </owners>
                        </default-result>
                    </results>
                </action>
                <action name="reject" text="拒绝">
                    <results>
                        <default-result exit-status="done" status="-2"/>
                    </results>
                </action>
                <action name="success" text="通过">
                    <results>
                        <default-result exit-status="done" step="9" status="queue">
                            <owners>
                                <owner type="users" props="100"/>
                            </owners>
                        </default-result>
                    </results>
                </action>
            </actions>
        </step>
        <step id="9" name="权证进件">
            <actions>
                <action name="rollback" text="回退">
                    <results>
                        <default-result exit-status="done" step="${rollback_id}" status="queue">
                            <owners>
                                <owner type="variable" props="${rollback_uid}"/>
                            </owners>
                        </default-result>
                    </results>
                </action>
                <action name="assignment" text="指派专员">
                    <results>
                        <default-result exit-status="done" split="3" />
                    </results>
                </action>
            </actions>
        </step>
        <step id="10" name="开卡">
            <actions>
                <action name="success" text="开卡完成">
                    <results>
                        <default-result exit-status="done" step="12" status="queue">
                            <owners>
                                <owner type="users" props="18"/>
                            </owners>
                        </default-result>
                    </results>
                </action>
            </actions>
        </step>
        <step id="11" name="贷款审批">
            <actions>
                <action name="rollback" text="贷款未通过">
                    <results>
                        <default-result exit-status="done" step="9" status="supplement">
                            <owners>
                                <owner type="users" props="100"/>
                            </owners>
                        </default-result>
                    </results>
                </action>
                <action name="success" text="贷款通过">
                    <results>
                        <default-result exit-status="done" join="3" />
                    </results>
                </action>
            </actions>
        </step>
        <step id="12" name="控卡">
            <actions>
                <action name="rollback" text="回退">
                    <results>
                        <default-result status="queue" step="${rollback_id}" exit-status="done">
                            <owners>
